// Run this script to seed sample job data: node --env-file=.env scripts/seed.js

const mongoose = require('mongoose');

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error('Please set MONGODB_URI in your environment');
  process.exit(1);
}

const jobSchema = new mongoose.Schema({
  title: String,
  organization: String,
  organizationFullName: String,
  category: {
    type: String,
    enum: ['PSU', 'CENTRAL', 'DEFENCE', 'RAILWAY', 'STATE', 'GENERAL'],
  },
  jobType: {
    type: String,
    enum: ['GATE', 'NON_GATE', 'MIXED'],
  },
  eligibleBranches: [String],
  openToNonEngineering: Boolean,
  numberOfPositions: Number,
  salary: String,
  ageLimit: String,
  eligibility: [String],
  eligibilityFinalYear: Boolean,
  applicationUrl: String,
  deadline: Date,
  status: {
    type: String,
    enum: ['OPEN', 'CLOSING_SOON', 'CLOSED', 'EXAM_PHASE', 'RESULT', 'INTERVIEW'],
  },
  description: String,
  qualification: String,
  minMarks: String,
  selectionProcess: String,
  bond: String,
  timeline: [
    {
      event: String,
      date: String,
      description: String,
      status: {
        type: String,
        enum: ['COMPLETED', 'ACTIVE', 'UPCOMING'],
      },
    },
  ],
  importantNotes: [String],
  isNewJob: Boolean,
  showPhases: Boolean,
  createdAt: Date,
  updatedAt: Date,
});

const Job = mongoose.models.Job || mongoose.model('Job', jobSchema);

const notificationSchema = new mongoose.Schema({
  text: String,
  createdAt: Date,
  updatedAt: Date,
});

const Notification = mongoose.models.Notification || mongoose.model('Notification', notificationSchema);

// ─── Synced from live MongoDB Atlas on 2026-06-13 ───────────────────────────
const sampleJobs = [
  {
    title: 'Junior Engineer (JE)',
    organization: 'BHEL',
    organizationFullName: 'Bharat Heavy Electricals Ltd',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['ME', 'EE'],
    openToNonEngineering: false,
    numberOfPositions: 1200,
    salary: '₹40,000 - ₹1,40,000/mo',
    ageLimit: '18-27 yrs (SC/ST +5, OBC +3)',
    eligibility: [
      'BE/B.Tech in Mechanical or Electrical Engineering',
      'Minimum 60% aggregate or equivalent CGPA in degree',
      'Valid GATE 2026 scorecard in respective paper',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://careers.bhel.in/',
    deadline: new Date('2026-05-28T00:00:00.000Z'),
    status: 'CLOSED',
    description: 'BHEL is recruiting Junior Engineers across major manufacturing units. GATE 2026 score is mandatory. Selected candidates will be posted across India - Haridwar, Bhopal, Trichy, Ranipet.',
    qualification: 'B.Tech / BE (Relevant Branch)',
    minMarks: '60% aggregate',
    selectionProcess: 'GATE Score -> Document Verification -> Medical',
    bond: 'No bond',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '12 May 2026', description: 'Official PDF available on bhel.in', status: 'COMPLETED' },
      { event: 'Application Window Open', date: '20 May 2026', description: 'Online applications active', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '15 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'GATE Score Shortlisting', date: 'Aug 2026', description: 'GATE 2024/2025/2026 scores considered', status: 'UPCOMING' },
      { event: 'Document Verification', date: 'Sep 2026', description: 'At corporate office, New Delhi', status: 'UPCOMING' },
      { event: 'Medical Examination', date: 'Oct 2026', description: 'At BHEL authorized hospitals', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Verify all details on the official organisation website before applying.',
      'Keep ready: Degree certificate, GATE scorecard (if required), ID proof, caste certificate.',
      'Application fee may apply - check official notification.',
      'Age/qualification relaxation for reserved categories as per Govt norms.',
    ],
  },
  {
    title: 'Scientist / Engineer SC',
    organization: 'ISRO',
    organizationFullName: 'Indian Space Research Organisation',
    category: 'DEFENCE',
    jobType: 'NON_GATE',
    eligibleBranches: ['ECE', 'CSE', 'ME'],
    openToNonEngineering: false,
    numberOfPositions: 320,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: '18-35 yrs (as of last date)',
    eligibility: [
      'BE/B.Tech or equivalent in first class with aggregate minimum of 65% marks',
      'M.Tech students can apply if UG criteria met',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://www.isro.gov.in/Careers.html',
    deadline: new Date('2026-04-12T00:00:00.000Z'),
    status: 'CLOSED',
    description: "ISRO Centralised Recruitment Board (ICRB) is inviting applications for Scientist/Engineer 'SC' posts. Recruitment will be based on a written test followed by interview.",
    qualification: 'B.Tech / BE or equivalent',
    minMarks: '65% aggregate or 6.84 CGPA',
    selectionProcess: 'Written Test -> Personal Interview',
    bond: 'No bond',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: '1 May 2026', description: 'Official notification published', status: 'COMPLETED' },
      { event: 'Application Form Open', date: '10 May 2026', description: 'Online registration started', status: 'COMPLETED' },
      { event: 'Last Date of Registration', date: '30 Jun 2026', description: 'Fees must be paid by this date', status: 'ACTIVE' },
      { event: 'Written Examination', date: 'Aug 2026', description: 'Scheduled in major cities', status: 'UPCOMING' },
      { event: 'Interview Call Letters', date: 'Sep 2026', description: 'Shortlist based on exam cutoffs', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Candidates awaiting final results are eligible to apply.',
      'Written exam pattern: 80 Multiple Choice Questions (MCQ) of 1 mark each.',
    ],
  },
  {
    title: 'Engineer Trainee (ET)',
    organization: 'NTPC',
    organizationFullName: 'National Thermal Power Corporation',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['ME', 'EE'],
    openToNonEngineering: false,
    numberOfPositions: 800,
    salary: '₹40,000 - ₹1,40,000/mo + DA',
    ageLimit: 'Max 27 years',
    eligibility: [
      'Full time Bachelor degree in Engineering with not less than 65% marks',
      'GATE 2026 qualification',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://careers.ntpc.co.in/',
    deadline: new Date('2026-05-29T00:00:00.000Z'),
    status: 'CLOSED',
    description: 'NTPC is looking for promising, energetic young engineers for Executive Trainee positions. Training is for 1 year followed by regular placement.',
    qualification: 'Full-time BE / B.Tech',
    minMarks: '65% aggregate (55% for SC/ST/PwBD)',
    selectionProcess: 'GATE score followed by GD and Personal Interview',
    bond: 'Service Agreement Bond of ₹2,50,000',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Notification Out', date: '10 Jun 2026', description: 'Detailed advt released', status: 'COMPLETED' },
      { event: 'Online Registration', date: '18 Jun 2026', description: 'Applications start online', status: 'ACTIVE' },
      { event: 'Last Date of Application', date: '30 Jul 2026', description: 'Last day to apply online', status: 'UPCOMING' },
      { event: 'GD & Interview', date: 'Sep 2026', description: 'Conducted at regional headquarters', status: 'UPCOMING' },
    ],
    importantNotes: [
      'SC/ST/PwBD candidates are exempted from registration fees.',
    ],
  },
  {
    title: 'Scientific Officer (OCES/DGFS)',
    organization: 'BARC',
    organizationFullName: 'Bhabha Atomic Research Centre',
    category: 'CENTRAL',
    jobType: 'MIXED',
    eligibleBranches: ['ME', 'CHEMICAL', 'METALLURGY', 'MINING'],
    openToNonEngineering: false,
    numberOfPositions: 220,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: 'Max 26 years',
    eligibility: [
      'BE/B.Tech/B.Sc (Engg) with minimum 60% aggregate',
      'Selection based on Online Exam OR GATE scorecard',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://barconlineexam.com/',
    deadline: new Date('2026-01-31T00:00:00.000Z'),
    status: 'CLOSED',
    description: 'BARC Training Schools recruit OCES and DGFS Scientific Officers. Highly competitive program for research-oriented engineers.',
    qualification: 'BE / B.Tech / B.Sc (Engg)',
    minMarks: '60% marks',
    selectionProcess: 'Online Test or GATE Score -> Personal Interview',
    bond: '3 Years Service Bond',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Advt Published', date: '10 Feb 2026', description: 'National news notification', status: 'COMPLETED' },
      { event: 'Online Exam Slot Booking', date: 'Apr 2026', description: 'Test booking active', status: 'COMPLETED' },
      { event: 'BARC Online Exam', date: '1-10 Jun 2026', description: 'CBT examination across centres', status: 'COMPLETED' },
      { event: 'Interview Shortlists', date: '15 Jun 2026', description: 'Releasing lists on portal', status: 'ACTIVE' },
      { event: 'Personal Interviews', date: 'Jul-Aug 2026', description: 'At BARC Training School, Mumbai', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Candidates shortlisted through GATE do not need to appear for online test.',
    ],
  },
  {
    title: 'Graduate Engineer Trainee',
    organization: 'HPCL',
    organizationFullName: 'Hindustan Petroleum Corporation Ltd',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['ME', 'EE', 'CIVIL', 'CHEMICAL'],
    openToNonEngineering: false,
    numberOfPositions: 290,
    salary: '₹50,000 - ₹1,60,000/mo',
    ageLimit: 'Max 25 years',
    eligibility: [
      'Four-year full time Engineering degree with 60% marks',
      'Selection via computer-based test (CBT) conducted by HPCL',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.hindustanpetroleum.com/',
    deadline: new Date('2026-06-05T23:59:59.000Z'),
    status: 'CLOSED',
    description: 'HPCL GET recruitment through proprietary examination. High pay package PSU with multiple core discipline posts.',
    qualification: 'Four Year BE / B.Tech',
    minMarks: '60% (50% for SC/ST/PwBD)',
    selectionProcess: 'Computer Based Test -> Group Task -> Personal Interview',
    bond: '4 Years Service Bond (₹1,50,000)',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Advt Out', date: '10 Apr 2026', description: 'Notification detailed copy', status: 'COMPLETED' },
      { event: 'Registration Closes', date: '5 Jun 2026', description: 'Closed on official portal', status: 'COMPLETED' },
      { event: 'CBT Exams', date: 'Jul 2026', description: 'To be held online', status: 'UPCOMING' },
    ],
    importantNotes: [
      'No GATE score required. Proprietary syllabus includes General Aptitude and Technical sections.',
    ],
  },
  {
    title: 'Research Associate (Aero)',
    organization: 'DRDO - ADE',
    organizationFullName: 'Aeronautical Development Establishment',
    category: 'DEFENCE',
    jobType: 'NON_GATE',
    eligibleBranches: ['ME', 'ECE'],
    openToNonEngineering: false,
    numberOfPositions: 15,
    salary: '₹54,000/mo',
    ageLimit: 'Max 28 years (General)',
    eligibility: [
      'PhD or equivalent degree in Aeronautical/Mechanical/Electronics OR M.Tech with 3 years research experience',
      'No GATE score required. Selection based on interview.',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.drdo.gov.in/',
    deadline: new Date('2026-03-24T00:00:00.000Z'),
    status: 'CLOSED',
    description: 'Aeronautical Development Establishment (ADE) is holding walk-in/scheduled interviews for Research Associates in aerospace development.',
    qualification: 'M.Tech / PhD in engineering',
    minMarks: 'First class in PG',
    selectionProcess: 'Screening -> Interview Board',
    bond: 'No bond',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Interview Notification', date: '2 Jun 2026', description: 'ADE advertisement published', status: 'COMPLETED' },
      { event: 'Application Submission Last Date', date: '29 Jun 2026', description: 'Submit via email/post', status: 'ACTIVE' },
      { event: 'Interview Date', date: 'Jul 2026', description: 'Conducted at ADE Bangalore', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Fellowship is initially for a period of two years.',
    ],
  },
  {
    title: 'Deputy Manager (Technical)',
    organization: 'NHAI',
    organizationFullName: 'National Highways Authority of India',
    category: 'CENTRAL',
    jobType: 'GATE',
    eligibleBranches: ['CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 120,
    salary: '₹15,600 - ₹39,100 + GP 5,400/mo',
    ageLimit: 'Max 30 years',
    eligibility: [
      'Degree in Civil Engineering from recognized university',
      'Valid GATE 2026 score in Civil Engineering paper',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://nhai.gov.in/',
    deadline: new Date('2026-06-01T23:59:59.000Z'),
    status: 'CLOSED',
    description: 'NHAI is recruiting Deputy Managers in Civil engineering through GATE 2026. Permanent jobs under Central Govt.',
    qualification: 'Degree in Civil Engineering',
    minMarks: 'Pass standard in degree',
    selectionProcess: 'GATE Score card selection directly',
    bond: 'Service agreement bond of 2 years',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: '10 Apr 2026', description: 'Detailed notifications on nhai.gov.in', status: 'COMPLETED' },
      { event: 'Application Link Close', date: '1 Jun 2026', description: 'Closed online submissions', status: 'COMPLETED' },
      { event: 'Shortlisted candidates list', date: 'Jul 2026', description: 'Selected list to be published', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Selection is direct based on GATE score; no interviews are scheduled.',
    ],
  },
  {
    title: 'Combined Graduate Level (CGL) 2026',
    organization: 'SSC',
    organizationFullName: 'Staff Selection Commission',
    category: 'GENERAL',
    jobType: 'NON_GATE',
    eligibleBranches: ['CSE', 'ECE', 'ME', 'CIVIL', 'MINING', 'METALLURGY', 'PRODUCTION', 'CHEMICAL'],
    openToNonEngineering: true,
    numberOfPositions: 17000,
    salary: '₹25,500 - ₹1,51,100/mo',
    ageLimit: '18-32 years (varies by post)',
    eligibility: [
      "Bachelor's Degree in any discipline from a recognised university",
      'No engineering degree required — open to all graduates',
      'Selection: Tier-I CBT → Tier-II CBT → Skill Test / Document Verification',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://ssc.gov.in/',
    deadline: new Date('2026-06-22T00:00:00.000Z'),
    status: 'OPEN',
    description: "SSC CGL 2026 is one of the largest central government recruitment exams open to all graduates. Posts include Inspector, Auditor, Tax Assistant, Sub-Inspector (CBI), Statistical Investigator, and more across central ministries and departments.",
    qualification: "Any Bachelor's Degree (Engineering graduates can also apply)",
    minMarks: 'Pass standard in graduation',
    selectionProcess: 'Tier-I CBT → Tier-II CBT → Skill Test / Document Verification',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Official Notification Released', date: '22 Jun 2026', description: 'SSC CGL 2026 detailed advt on ssc.gov.in', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '22 Jun 2026', description: 'Registration on ssc.gov.in portal', status: 'ACTIVE' },
      { event: 'Application Last Date', date: '10 Aug 2026', description: 'Submit before 11:59 PM', status: 'UPCOMING' },
      { event: 'Tier-I Exam (CBT)', date: 'Sep–Oct 2026', description: 'Computer-based test across exam centres', status: 'UPCOMING' },
      { event: 'Tier-II Exam (CBT)', date: 'Dec 2026', description: 'For shortlisted candidates from Tier-I', status: 'UPCOMING' },
      { event: 'Skill Test / Document Verification', date: 'Jan–Feb 2027', description: 'Post-specific skill tests and DV', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Open to graduates from any stream — not limited to engineering.',
      'Engineers are eligible and often benefit from technical aptitude in the exam.',
      'Negative marking: 0.50 marks for each wrong answer in Tier-I and Tier-II.',
      'Age relaxation: SC/ST +5 yrs, OBC +3 yrs, PwBD +10 yrs, Ex-Servicemen as per norms.',
      'Over 17,000 vacancies expected across Group B and Group C posts.',
    ],
  },
  {
    title: 'Management Trainee (MT)',
    organization: 'CIL',
    organizationFullName: 'Coal India Limited',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['CSE', 'CHEMICAL', 'ECE', 'ME', 'CIVIL', 'MINING', 'METALLURGY', 'PRODUCTION'],
    openToNonEngineering: false,
    numberOfPositions: 660,
    salary: '₹50,000 - ₹1,60,000/mo (E-2 Grade)',
    ageLimit: '30 years',
    eligibility: [
      'BE/B.Tech',
      'Diploma',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.coalindia.in/career-cil/jobs-coal-india/',
    deadline: new Date('2026-06-21T00:00:00.000Z'),
    status: 'OPEN',
    description: '',
    qualification: 'BE/B.Tech',
    minMarks: '60%',
    selectionProcess: 'CBT Only',
    bond: 'No Bond',
    isNewJob: true,
    showPhases: false,
    timeline: [],
    importantNotes: [],
  },
  {
    title: 'Junior Telecom Officer (JTO)',
    organization: 'BSNL',
    organizationFullName: 'Bharat Sanchar Nigam Limited',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['ECE', 'EE', 'CSE'],
    openToNonEngineering: false,
    numberOfPositions: 100,
    salary: '₹16,400 - ₹40,500/mo',
    ageLimit: '20-30 yrs (SC/ST +5, OBC +3)',
    eligibility: [
      'B.E / B.Tech / M.Sc / M.Tech in relevant discipline from a recognised university',
      'Age 20–30 years as on 03 July 2026',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://bsnl.co.in/',
    deadline: new Date('2026-07-03T10:00:00.000Z'),
    status: 'OPEN',
    description: 'BSNL is recruiting 100 Junior Telecom Officers (Group A Engineering Cadre) through direct recruitment. Selection is through a Computer Based Test followed by document verification and medical examination. Selected candidates will be allotted a Circle based on merit and preference.',
    qualification: 'B.E / B.Tech / M.Sc / M.Tech (relevant discipline)',
    minMarks: 'Pass standard',
    selectionProcess: 'Computer Based Test (CBT) -> Document Verification -> Medical Examination',
    bond: 'Service bond of ₹6,00,000 for minimum 5 years',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '26 May 2026', description: 'Advt No. BSNLCO-11/12(11)/1/2026-RECTT-CO published', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '4 Jun 2026', description: 'Registration active on bsnl.co.in', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '3 Jul 2026', description: 'Submit before 10:00 AM', status: 'ACTIVE' },
      { event: 'Computer Based Test', date: 'Aug 2026', description: 'CBT date to be notified via admit card', status: 'UPCOMING' },
      { event: 'Document Verification', date: 'Sep 2026', description: 'At respective BSNL Circle offices', status: 'UPCOMING' },
      { event: 'Medical Examination', date: 'Sep-Oct 2026', description: 'At BSNL authorised hospitals', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Candidates may give preferences for up to all 21 BSNL Circles.',
      'Application fee: ₹2,000 for General/OBC/EWS; ₹1,000 for SC/ST/PwBD.',
      'Negative marking: +4 for correct, -1 for wrong answer.',
      'JTO is a Circle Cadre post — no inter-circle transfer after appointment.',
      'Verify all details on the official BSNL website before applying.',
    ],
  },
  {
    title: 'Management Trainee (MT) – E-1 Grade',
    organization: 'CIL',
    organizationFullName: 'Coal India Limited',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['CIVIL', 'ME', 'EE', 'CSE', 'ECE', 'MINING', 'CHEMICAL', 'PRODUCTION'],
    openToNonEngineering: false,
    numberOfPositions: 660,
    salary: '₹60,000 - ₹1,80,000/mo (E-1 Grade)',
    ageLimit: 'Max 30 yrs as on 30 Apr 2026 (SC/ST +5, OBC +3)',
    eligibility: [
      'Full-time B.E / B.Tech / B.Sc (Engg) / M.Tech / M.Sc / MCA in relevant discipline with minimum 60% marks (55% for SC/ST/PwBD)',
      'Final year students of academic year 2025–26 expecting results by 31 Aug 2026 are also eligible',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://www.coalindia.in/career-cil/jobs-coal-india/',
    deadline: new Date('2026-06-21T18:00:00.000Z'),
    status: 'OPEN',
    description: 'Coal India Limited (CIL), a Maharatna PSU under Ministry of Coal, has announced 660 Management Trainee vacancies in E-1 Grade across 9 disciplines: Civil, Electrical, Mechanical, System, E&T, Geology, Industrial Engineering, Rajbhasha, and Company Secretary. Selection is through a Computer Based Test only.',
    qualification: 'Full-time B.E / B.Tech / M.Tech / M.Sc / MCA',
    minMarks: '60% aggregate (55% for SC/ST/PwBD)',
    selectionProcess: 'Computer Based Test (CBT) -> Document Verification -> Medical',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '5 May 2026', description: 'Advt No. 03/2026 published on coalindia.in', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '12 May 2026', description: 'Registration active from 10:00 hrs', status: 'COMPLETED' },
      { event: 'Application Last Date (Extended)', date: '21 Jun 2026', description: 'Submit before 18:00 hrs', status: 'ACTIVE' },
      { event: 'Computer Based Test', date: 'TBA', description: 'CBT date to be notified separately', status: 'UPCOMING' },
      { event: 'Document Verification', date: 'TBA', description: 'Conducted at CIL/subsidiary offices', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Application fee: ₹1,180 for General/OBC (Creamy & Non-Creamy)/EWS; SC/ST/PwBD/CIL employees are exempted.',
      'Rounding of percentage not acceptable — even 59.99% will not be treated as 60%.',
      'Online, part-time, and distance learning degrees are NOT acceptable for technical disciplines.',
      'Verify all details on the official Coal India website before applying.',
    ],
  },
  {
    title: 'Assistant Executive Engineer (Civil)',
    organization: 'TSPSC',
    organizationFullName: 'Telangana State Public Service Commission',
    category: 'STATE',
    jobType: 'NON_GATE',
    eligibleBranches: ['CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 222,
    salary: '₹53,100 - ₹1,67,800/mo',
    ageLimit: '18-44 yrs (as per Telangana Govt norms)',
    eligibility: [
      'Bachelor\'s degree in Civil Engineering from a recognised university',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://tgpsc.gov.in/',
    deadline: new Date('2026-07-13T23:59:59.000Z'),
    status: 'OPEN',
    description: 'TSPSC (Telangana State Public Service Commission) has released AEE Civil recruitment 2026 for 222 posts under Transport, Roads and Buildings Department. Selection is through a written test (Paper-I General Studies + Paper-II Civil Engineering) and document verification.',
    qualification: 'B.E / B.Tech in Civil Engineering',
    minMarks: 'Pass standard',
    selectionProcess: 'Written Test (Paper I + Paper II) -> Document Verification',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '2 Jun 2026', description: 'Notification No. 01/G/RB/2026 on tgpsc.gov.in', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '6 Jun 2026', description: 'OTR registration and application active', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '13 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'Written Exam (Paper I)', date: 'TBA', description: 'General Studies & General Abilities (bilingual)', status: 'UPCOMING' },
      { event: 'Written Exam (Paper II)', date: 'TBA', description: 'Civil Engineering — 150 min, 150 marks', status: 'UPCOMING' },
      { event: 'Document Verification', date: 'TBA', description: 'At TSPSC office, Hyderabad', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Complete OTR (One Time Registration) on tgpsc.gov.in before applying.',
      'Paper I is bilingual (English and Telugu); Paper II is in English.',
      'Each paper is 150 minutes duration.',
      'Verify all details on the official TGPSC website before applying.',
    ],
  },
  {
    title: 'Assistant Executive Engineer (Electrical)',
    organization: 'TSPSC',
    organizationFullName: 'Telangana State Public Service Commission',
    category: 'STATE',
    jobType: 'NON_GATE',
    eligibleBranches: ['EE'],
    openToNonEngineering: false,
    numberOfPositions: 49,
    salary: '₹53,100 - ₹1,67,800/mo',
    ageLimit: '18-44 yrs (as per Telangana Govt norms)',
    eligibility: [
      'Bachelor\'s degree in Electrical Engineering from a recognised university',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://tgpsc.gov.in/',
    deadline: new Date('2026-07-15T23:59:59.000Z'),
    status: 'OPEN',
    description: 'TSPSC has released AEE Electrical recruitment 2026 for 49 posts under Transport, Roads and Buildings Department. Selection is through a written test and document verification.',
    qualification: 'B.E / B.Tech in Electrical Engineering',
    minMarks: 'Pass standard',
    selectionProcess: 'Written Test (Paper I + Paper II) -> Document Verification',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: '2 Jun 2026', description: 'Notification on tgpsc.gov.in', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '8 Jun 2026', description: 'OTR registration and application active', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '15 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'Written Examination', date: 'TBA', description: 'Paper I (GS) + Paper II (Electrical)', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Complete OTR (One Time Registration) on tgpsc.gov.in before applying.',
      'Verify all details on the official TGPSC website before applying.',
    ],
  },
  {
    title: 'Assistant Environmental Engineer',
    organization: 'TSPSC',
    organizationFullName: 'Telangana State Public Service Commission',
    category: 'STATE',
    jobType: 'NON_GATE',
    eligibleBranches: ['CIVIL', 'CHEMICAL'],
    openToNonEngineering: false,
    numberOfPositions: 19,
    salary: '₹53,100 - ₹1,67,800/mo',
    ageLimit: '18-44 yrs (as per Telangana Govt norms)',
    eligibility: [
      'Bachelor\'s degree in Civil or Chemical Engineering from a recognised university',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://tgpsc.gov.in/',
    deadline: new Date('2026-07-17T23:59:59.000Z'),
    status: 'OPEN',
    description: 'TSPSC has released Assistant Environmental Engineer recruitment 2026 for 19 posts under Telangana Pollution Control Board. Selection is through a written test and document verification.',
    qualification: 'B.E / B.Tech in Civil or Chemical Engineering',
    minMarks: 'Pass standard',
    selectionProcess: 'Written Test (Paper I + Paper II) -> Document Verification',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: '2 Jun 2026', description: 'Notification on tgpsc.gov.in', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '10 Jun 2026', description: 'OTR registration and application active', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '17 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'Written Examination', date: 'TBA', description: 'Paper I (GS) + Paper II (Environmental/Civil/Chemical)', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Complete OTR (One Time Registration) on tgpsc.gov.in before applying.',
      'Verify all details on the official TGPSC website before applying.',
    ],
  },
  {
    title: 'Project Engineer / Project Associate & more',
    organization: 'C-DAC',
    organizationFullName: 'Centre for Development of Advanced Computing',
    category: 'CENTRAL',
    jobType: 'NON_GATE',
    eligibleBranches: ['CSE', 'ECE', 'EE', 'ME', 'CIVIL', 'CHEMICAL'],
    openToNonEngineering: false,
    numberOfPositions: 951,
    salary: 'As per C-DAC norms (contractual)',
    ageLimit: 'Varies by post',
    eligibility: [
      'B.E / B.Tech / M.E / M.Tech / MCA / M.Sc / Ph.D / ITI / Diploma as per post requirements',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.cdac.in/',
    deadline: new Date('2026-06-20T23:59:59.000Z'),
    status: 'OPEN',
    description: 'C-DAC has released recruitment for 951 contractual positions across 11 centres in India for posts including Project Engineer, Senior Project Engineer, Project Associate, Project Technician, Project Support Staff, and Program Manager across multiple disciplines.',
    qualification: 'B.E / B.Tech / M.Tech / MCA / M.Sc / ITI / Diploma (as per post)',
    minMarks: 'Varies by post',
    selectionProcess: 'Shortlisting -> Interview',
    bond: 'No bond (contractual engagement)',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: 'Jun 2026', description: 'Official notification on cdac.in', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '20 Jun 2026', description: 'Submit before 11:59 PM on cdac.in', status: 'ACTIVE' },
      { event: 'Shortlisting & Interview', date: 'TBA', description: 'Merit-based shortlisting then interview', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Posts are contractual in nature, not permanent government employment.',
      'Multiple disciplines and centres — check post-wise eligibility carefully.',
      'Regularly check cdac.in for corrigendum and updates.',
      'Verify all details on the official C-DAC website before applying.',
    ],
  },
  {
    title: 'Vidyut Sahayak – Junior Engineer (Electrical)',
    organization: 'MGVCL / GUVNL',
    organizationFullName: 'Madhya Gujarat Vij Company Ltd / Gujarat Urja Vikas Nigam Ltd',
    category: 'STATE',
    jobType: 'NON_GATE',
    eligibleBranches: ['EE'],
    openToNonEngineering: false,
    numberOfPositions: 183,
    salary: '₹48,100/mo (Yr 1); ₹50,700/mo (Yr 2); then ₹45,400 - ₹1,01,200/mo on regularisation',
    ageLimit: 'As per GUVNL norms (calculated as on advertisement date 10 Jun 2026)',
    eligibility: [
      'B.E / B.Tech in Electrical Engineering from a recognised university',
      'Minimum 85% of selections reserved for Gujarat domicile candidates',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.mgvcl.com/career',
    deadline: new Date('2026-07-02T23:59:59.000Z'),
    status: 'OPEN',
    description: 'MGVCL on behalf of GUVNL and its subsidiaries (MGVCL, DGVCL, UGVCL, PGVCL, GETCO) has announced 183 Vidyut Sahayak (Junior Engineer – Electrical) vacancies. Initial engagement is for 2 years; on successful completion, candidates may be appointed as regular JE-Electrical. Selection is through a two-tier Computer Based Test.',
    qualification: 'B.E / B.Tech in Electrical Engineering',
    minMarks: 'Pass standard',
    selectionProcess: 'Tier-1 CBT (General Aptitude, 100 marks) -> Tier-2 CBT (Electrical Engg, 100 marks) -> Document Verification -> Medical',
    bond: 'No inter-company transfer permitted after appointment',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '10 Jun 2026', description: 'Official notification on mgvcl.com/career', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '12 Jun 2026', description: 'Registration active on mgvcl.com/career', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '2 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'Tier-1 CBT', date: 'TBA', description: 'General Aptitude — 100 marks', status: 'UPCOMING' },
      { event: 'Tier-2 CBT', date: 'TBA', description: 'Electrical Engineering — 100 marks; final merit based on Tier-2', status: 'UPCOMING' },
      { event: 'Document Verification & Medical', date: 'TBA', description: 'For shortlisted candidates', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Application fee: ₹500 (Unreserved); ₹250 (Reserved/PwD). Non-refundable.',
      'Indicate company preference (MGVCL, DGVCL, UGVCL, PGVCL, GETCO) at time of application — cannot be revised later.',
      'Minimum 85% seats reserved for Gujarat domicile candidates; Domicile Certificate required.',
      'Non-Gujarat domicile candidates from reserved categories treated as UR.',
      'Verify all details on official mgvcl.com website before applying.',
    ],
  },
  {
    title: 'QA/QC Engineer & Safety Officer',
    organization: 'CEIL',
    organizationFullName: 'Central Electronics Ltd (India)',
    category: 'CENTRAL',
    jobType: 'NON_GATE',
    eligibleBranches: ['ME', 'EE', 'ECE', 'CIVIL', 'CHEMICAL'],
    openToNonEngineering: false,
    numberOfPositions: 85,
    salary: 'As per CEIL norms',
    ageLimit: 'As per CEIL norms',
    eligibility: [
      'Engineering Graduate or Diploma in Engineering (relevant branch)',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.celindia.co.in/',
    deadline: new Date('2026-06-15T23:59:59.000Z'),
    status: 'CLOSING_SOON',
    description: 'Central Electronics Ltd (a Govt of India Enterprise) is recruiting for QA/QC Engineers, Safety Officers, HR Associates, and Officers across its units.',
    qualification: 'Engineering Graduate / Diploma in Engineering',
    minMarks: 'Pass standard',
    selectionProcess: 'Shortlisting -> Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: 'Jun 2026', description: 'Notification on celindia.co.in', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '15 Jun 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
    ],
    importantNotes: [
      'Closing soon — apply immediately.',
      'Verify all details on the official CEIL website before applying.',
    ],
  },
  {
    title: 'Project Engineer-I',
    organization: 'BEL',
    organizationFullName: 'Bharat Electronics Limited',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['ECE', 'EE', 'CSE'],
    openToNonEngineering: false,
    numberOfPositions: 4,
    salary: 'As per BEL norms (contractual)',
    ageLimit: 'As per BEL norms',
    eligibility: [
      'B.Tech / B.E or B.Sc in relevant discipline from a recognised institution',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://bel-india.in/',
    deadline: new Date('2026-06-16T23:59:59.000Z'),
    status: 'CLOSING_SOON',
    description: 'Bharat Electronics Limited (BEL) is recruiting Project Engineer-I on a contractual basis. Candidates with electronics/electrical/computer science backgrounds are eligible.',
    qualification: 'B.Tech / B.E / B.Sc (relevant discipline)',
    minMarks: 'Pass standard',
    selectionProcess: 'Shortlisting -> Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: 'May 2026', description: 'Advt on bel-india.in', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '16 Jun 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
    ],
    importantNotes: [
      'Post is contractual in nature.',
      'Closing soon — apply immediately.',
      'Verify all details on the official BEL website before applying.',
    ],
  },
  {
    title: 'Junior Research Fellow (JRF)',
    organization: 'ISRO URSC',
    organizationFullName: 'U R Rao Satellite Centre, ISRO',
    category: 'DEFENCE',
    jobType: 'NON_GATE',
    eligibleBranches: ['ECE', 'EE', 'ME', 'CSE'],
    openToNonEngineering: false,
    numberOfPositions: 17,
    salary: '₹37,000/mo (JRF); ₹42,000/mo (SRF after 2 years)',
    ageLimit: 'Max 28 yrs as on 11 Jul 2026 (SC/ST +5, OBC +3)',
    eligibility: [
      'M.E / M.Tech or M.Sc in relevant discipline (VLSI, Power Electronics, Thermal, Optical Engg, etc.)',
      'Must have qualified GATE / CSIR-UGC NET / JAM / JEST or equivalent national-level exam',
      'Only passed candidates eligible; students awaiting results are NOT eligible',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.isro.gov.in/',
    deadline: new Date('2026-07-11T23:59:59.000Z'),
    status: 'OPEN',
    description: 'ISRO\'s U R Rao Satellite Centre (URSC), Bengaluru has announced 17 Junior Research Fellow positions across 16 technical specialisations for advanced research in spacecraft development, VLSI, optical engineering, power electronics, thermal systems, and other domains. Advert No. URSC:02:2026.',
    qualification: 'M.E / M.Tech / M.Sc in relevant discipline',
    minMarks: 'First class in PG',
    selectionProcess: 'Initial Screening (GATE/NET score) -> Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '12 Jun 2026', description: 'Advt No. URSC:02:2026 on isro.gov.in', status: 'COMPLETED' },
      { event: 'Online Applications Open', date: '12 Jun 2026', description: 'Registration active on ISRO website', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '11 Jul 2026', description: 'Submit before portal closes', status: 'ACTIVE' },
      { event: 'Initial Screening', date: 'TBA', description: 'Based on GATE/NET score', status: 'UPCOMING' },
      { event: 'Interview', date: 'TBA', description: 'At URSC, Bengaluru', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Valid GATE / CSIR-UGC NET / JAM / JEST score is mandatory — no exemption.',
      'Fellowship is initially for 2 years; may be extended to SRF at ISRO/DOS/URSC discretion.',
      '11 Jul 2026 is the cut-off date for age and qualification determination.',
      'Verify all details on the official ISRO website before applying.',
    ],
  },
  {
    title: 'Young Professional (Grade-1 / Grade-2)',
    organization: 'IN-SPACe',
    organizationFullName: 'Indian National Space Promotion and Authorisation Centre (Dept of Space)',
    category: 'CENTRAL',
    jobType: 'NON_GATE',
    eligibleBranches: ['ECE', 'CSE', 'ME', 'EE', 'CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 10,
    salary: 'As per IN-SPACe norms',
    ageLimit: 'As per IN-SPACe norms',
    eligibility: [
      'Post Graduate Degree / Engineering Degree / Master\'s Degree in relevant discipline',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.inspace.gov.in/',
    deadline: new Date('2026-06-20T23:59:59.000Z'),
    status: 'OPEN',
    description: 'IN-SPACe (Indian National Space Promotion and Authorisation Centre), under the Department of Space, is recruiting Young Professionals at Grade-1 and Grade-2 levels for roles supporting India\'s growing private and public space ecosystem.',
    qualification: 'Engineering Degree / PG / Master\'s Degree (relevant discipline)',
    minMarks: 'Pass standard',
    selectionProcess: 'Shortlisting -> Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: 'Jun 2026', description: 'Notification on inspace.gov.in', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '20 Jun 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
    ],
    importantNotes: [
      'Verify all details on the official IN-SPACe website before applying.',
    ],
  },
  {
    title: 'Deputy Chief Engineer & more',
    organization: 'Oil India',
    organizationFullName: 'Oil India Limited',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['ME', 'EE', 'CIVIL', 'CHEMICAL', 'MINING'],
    openToNonEngineering: false,
    numberOfPositions: 10,
    salary: 'As per OIL norms (Grade D/E/F)',
    ageLimit: 'As per OIL norms',
    eligibility: [
      'B.Tech / B.E in relevant engineering discipline or M.Sc in relevant field',
      'Work experience required as per post',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.oil-india.com/',
    deadline: new Date('2026-06-28T23:59:59.000Z'),
    status: 'OPEN',
    description: 'Oil India Limited has announced vacancies for Economist, Deputy Chief Engineer and other Grade D/E/F level positions. These are experienced professional roles in India\'s premier oil & gas PSU.',
    qualification: 'B.Tech / B.E / M.Sc (relevant discipline)',
    minMarks: 'Pass standard',
    selectionProcess: 'Shortlisting -> Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: 'Jun 2026', description: 'Notification on oil-india.com', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '28 Jun 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
    ],
    importantNotes: [
      'Experienced professionals only — check post-wise experience requirements.',
      'Verify all details on the official Oil India website before applying.',
    ],
  },
  {
    title: 'Assistant Engineer',
    organization: 'GPSC',
    organizationFullName: 'Gujarat Public Service Commission',
    category: 'STATE',
    jobType: 'NON_GATE',
    eligibleBranches: ['CIVIL', 'ME'],
    openToNonEngineering: false,
    numberOfPositions: 26,
    salary: '₹44900-142400/mo',
    ageLimit: '35 yrs',
    eligibility: [
      'BE/B.Tech in Civil or Mechanical',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://gpsc.gujarat.gov.in/dashboard?stage=Advertisement',
    deadline: new Date('2026-06-19T00:00:00.000Z'),
    status: 'OPEN',
    description: `Educational Qualification Possesses:
(i) a bachelor's degree in Engineering (Mechanical) or in Technology (Mechanical) obtained from any of the Universities established or incorporated by or under the Central or State Act in India; or any other educational institution recognized as such or declared to be a deemed university under section 3 of the University Grants Commission Act, 1956; or possess an equivalent qualification recognized as such by the Government,
(ii) the basic knowledge of computer application as prescribed in the Gujarat Civil Services Classification and Recruitment (General) Rules, 1967, and
(iii) the adequate knowledge of Gujarati or Hindi or both.
Age: Maximum up to 35 years. (Age will be calculated as on the last date of receipt of application)
Pay Scale According to 7th pay commission pay matrix Level-08 (Rs.44900-142400/-)`,
    qualification: 'BE/B.Tech',
    minMarks: '',
    selectionProcess: 'Prelims (I & II)->Interview',
    bond: 'No',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Part-I (General Studies)', date: '26/07/2026', description: 'Prelims paper 1', status: 'UPCOMING' },
      { event: 'Part-II (Concerned Subject)', date: '30/08/2026', description: 'Prelims Paper 2', status: 'UPCOMING' },
      { event: 'Interview', date: 'Soon to be announced', description: '', status: 'UPCOMING' },
    ],
    importantNotes: [],
  },
];

const sampleNotifications = [
  { text: 'BHEL JE Recruitment 2026 – 1200 Posts Open | Apply before 15 Jul' },
  { text: 'ISRO Scientist/Engineer SC 2026 – Last Date 30 Jun' },
  { text: 'ONGC Graduate Trainee 2026 – Applications Open' },
  { text: 'NTPC Engineer Trainee 2026 – 800 Vacancies | GATE Score Required' },
  { text: 'DRDO Scientist B 2026 – Written Test on 25 Aug 2026' },
  { text: 'BEL Project Engineer 2026 – Apply Before 15 Jul' },
  { text: 'HAL Aerospace Engineer 2026 – Written Test Admit Cards Released' },
  { text: 'SSC CGL 2026 – 17,000+ Posts | All Graduates Eligible | Apply before 10 Aug' },
  { text: 'BSNL JTO 2026 – 100 Posts | Apply before 3 Jul 2026 | CBT in Aug 2026' },
  { text: 'Coal India MT 2026 – 660 Posts | Last Date Extended to 21 Jun 2026' },
  { text: 'TSPSC AEE Civil 2026 – 222 Posts | Apply before 13 Jul 2026' },
  { text: 'TSPSC AEE Electrical 2026 – 49 Posts | Apply before 15 Jul 2026' },
  { text: 'TSPSC Asst Environmental Engineer 2026 – 19 Posts | Apply before 17 Jul 2026' },
  { text: 'C-DAC Recruitment 2026 – 951 Posts | Apply before 20 Jun 2026' },
  { text: 'MGVCL / GUVNL JE (Electrical) 2026 – 183 Posts | Apply before 2 Jul 2026' },
  { text: 'CEIL Recruitment 2026 – 85+ Posts | Closing 15 Jun 2026 – Apply Now' },
  { text: 'BEL Project Engineer-I 2026 – 4 Posts | Closing 16 Jun 2026 – Apply Now' },
  { text: 'ISRO URSC JRF 2026 – 17 Posts | GATE/NET Required | Apply before 11 Jul 2026' },
  { text: 'IN-SPACe Young Professional 2026 – 10 Posts | Apply before 20 Jun 2026' },
  { text: 'Oil India Recruitment 2026 – DCE & more | Apply before 28 Jun 2026' },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Insert new jobs only — skip if duplicate (organization + title), never modify existing
    let jobsInserted = 0;
    let jobsSkipped = 0;
    for (const job of sampleJobs) {
      const result = await Job.findOneAndUpdate(
        { organization: job.organization, title: job.title },
        { $setOnInsert: job },
        { upsert: true, new: false }
      );
      if (result) {
        jobsSkipped++;
      } else {
        jobsInserted++;
      }
    }
    console.log(`✅ Jobs — inserted: ${jobsInserted}, skipped (already exist): ${jobsSkipped}`);

    // Insert new notifications only — skip if duplicate (text), never modify existing
    let notifsInserted = 0;
    let notifsSkipped = 0;
    for (const notif of sampleNotifications) {
      const result = await Notification.findOneAndUpdate(
        { text: notif.text },
        { $setOnInsert: notif },
        { upsert: true, new: false }
      );
      if (result) {
        notifsSkipped++;
      } else {
        notifsInserted++;
      }
    }
    console.log(`✅ Notifications — inserted: ${notifsInserted}, skipped (already exist): ${notifsSkipped}`);

    await mongoose.connection.close();
    console.log('Disconnected from MongoDB');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();
