// Run this script to seed sample job data: node --env-file=.env scripts/seed.js

const mongoose = require('mongoose');

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error('Please set MONGODB_URI in your environment');
  process.exit(1);
}

const jobSchema = new mongoose.Schema({
  title: String,
  organization: String,
  organizationFullName: String,
  category: {
    type: String,
    enum: ['PSU', 'CENTRAL', 'DEFENCE', 'RAILWAY', 'STATE'],
  },
  jobType: {
    type: String,
    enum: ['GATE', 'NON_GATE', 'MIXED'],
  },
  eligibleBranches: [String],
  openToNonEngineering: Boolean,
  numberOfPositions: Number,
  salary: String,
  ageLimit: String,
  eligibility: [String],
  eligibilityFinalYear: Boolean,
  applicationUrl: String,
  deadline: Date,
  status: {
    type: String,
    enum: ['OPEN', 'CLOSING_SOON', 'CLOSED', 'EXAM_PHASE', 'RESULT', 'INTERVIEW'],
  },
  description: String,
  qualification: String,
  minMarks: String,
  selectionProcess: String,
  bond: String,
  timeline: [
    {
      event: String,
      date: String,
      description: String,
      status: {
        type: String,
        enum: ['COMPLETED', 'ACTIVE', 'UPCOMING'],
      },
    },
  ],
  importantNotes: [String],
  isNewJob: Boolean,
  showPhases: Boolean,
  createdAt: Date,
  updatedAt: Date,
});

const Job = mongoose.models.Job || mongoose.model('Job', jobSchema);

const notificationSchema = new mongoose.Schema({
  text: String,
  createdAt: Date,
  updatedAt: Date,
});

const Notification = mongoose.models.Notification || mongoose.model('Notification', notificationSchema);

const sampleJobs = [
  {
    title: 'Junior Engineer (JE)',
    organization: 'BHEL',
    organizationFullName: 'Bharat Heavy Electricals Ltd',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['ME', 'EE'],
    openToNonEngineering: false,
    numberOfPositions: 1200,
    salary: '₹40,000 - ₹1,40,000/mo',
    ageLimit: '18-27 yrs (SC/ST +5, OBC +3)',
    eligibility: [
      'BE/B.Tech in Mechanical or Electrical Engineering',
      'Minimum 60% aggregate or equivalent CGPA in degree',
      'Valid GATE 2026 scorecard in respective paper',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://careers.bhel.in/',
    deadline: new Date('2026-07-15T23:59:59Z'),
    status: 'OPEN',
    description: 'BHEL is recruiting Junior Engineers across major manufacturing units. GATE 2026 score is mandatory. Selected candidates will be posted across India - Haridwar, Bhopal, Trichy, Ranipet.',
    qualification: 'B.Tech / BE (Relevant Branch)',
    minMarks: '60% aggregate',
    selectionProcess: 'GATE Score -> Document Verification -> Medical',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '12 May 2026', description: 'Official PDF available on bhel.in', status: 'COMPLETED' },
      { event: 'Application Window Open', date: '20 May 2026', description: 'Online applications active', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '15 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'GATE Score Shortlisting', date: 'Aug 2026', description: 'GATE 2024/2025/2026 scores considered', status: 'UPCOMING' },
      { event: 'Document Verification', date: 'Sep 2026', description: 'At corporate office, New Delhi', status: 'UPCOMING' },
      { event: 'Medical Examination', date: 'Oct 2026', description: 'At BHEL authorized hospitals', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Verify all details on the official organisation website before applying.',
      'Keep ready: Degree certificate, GATE scorecard (if required), ID proof, caste certificate.',
      'Application fee may apply - check official notification.',
      'Age/qualification relaxation for reserved categories as per Govt norms.',
    ],
  },
  {
    title: 'Scientist / Engineer SC',
    organization: 'ISRO',
    organizationFullName: 'Indian Space Research Organisation',
    category: 'DEFENCE',
    jobType: 'NON_GATE',
    eligibleBranches: ['ECE', 'CSE', 'ME'],
    openToNonEngineering: false,
    numberOfPositions: 320,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: '18-35 yrs (as of last date)',
    eligibility: [
      'BE/B.Tech or equivalent in first class with aggregate minimum of 65% marks',
      'M.Tech students can apply if UG criteria met',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://www.isro.gov.in/Careers.html',
    deadline: new Date('2026-06-30T23:59:59Z'),
    status: 'CLOSING_SOON',
    description: 'ISRO Centralised Recruitment Board (ICRB) is inviting applications for Scientist/Engineer \'SC\' posts. Recruitment will be based on a written test followed by interview.',
    qualification: 'B.Tech / BE or equivalent',
    minMarks: '65% aggregate or 6.84 CGPA',
    selectionProcess: 'Written Test -> Personal Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '1 May 2026', description: 'Official notification published', status: 'COMPLETED' },
      { event: 'Application Form Open', date: '10 May 2026', description: 'Online registration started', status: 'COMPLETED' },
      { event: 'Last Date of Registration', date: '30 Jun 2026', description: 'Fees must be paid by this date', status: 'ACTIVE' },
      { event: 'Written Examination', date: 'Aug 2026', description: 'Scheduled in major cities', status: 'UPCOMING' },
      { event: 'Interview Call Letters', date: 'Sep 2026', description: 'Shortlist based on exam cutoffs', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Candidates awaiting final results are eligible to apply.',
      'Written exam pattern: 80 Multiple Choice Questions (MCQ) of 1 mark each.',
    ],
  },
  {
    title: 'Graduate Trainee (GE/GD)',
    organization: 'ONGC',
    organizationFullName: 'Oil & Natural Gas Corporation',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['ME', 'CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 950,
    salary: '₹60,000 - ₹1,80,000/mo',
    ageLimit: 'Max 30 years (General)',
    eligibility: [
      'Graduate degree in Engineering with minimum 60% marks',
      'Valid GATE 2026 score in respective subject',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.ongcindia.com/',
    deadline: new Date('2026-08-01T23:59:59Z'),
    status: 'OPEN',
    description: 'ONGC recruits Graduate Trainees at E1 level through GATE scores. Selected candidates are placed across various onshore/offshore assets.',
    qualification: 'BE / B.Tech (Mechanical / Civil)',
    minMarks: '60% marks',
    selectionProcess: 'GATE Score (85%) + Interview (15%)',
    bond: '3 Years Service Bond (₹3,00,000)',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '5 Jun 2026', description: 'Detailed vacancy list out', status: 'COMPLETED' },
      { event: 'Application Window Open', date: '12 Jun 2026', description: 'Registration link active', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '1 Aug 2026', description: 'Closes at 11:59 PM', status: 'ACTIVE' },
      { event: 'Interview Round', date: 'Sep 2026', description: 'Shortlisted candidates interview', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Final year students are not eligible since GATE scorecards are required at submission.',
    ],
  },
  {
    title: 'Engineer Trainee (ET)',
    organization: 'NTPC',
    organizationFullName: 'National Thermal Power Corporation',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['ME', 'EE'],
    openToNonEngineering: false,
    numberOfPositions: 800,
    salary: '₹40,000 - ₹1,40,000/mo + DA',
    ageLimit: 'Max 27 years',
    eligibility: [
      'Full time Bachelor degree in Engineering with not less than 65% marks',
      'GATE 2026 qualification',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://careers.ntpc.co.in/',
    deadline: new Date('2026-07-30T23:59:59Z'),
    status: 'OPEN',
    description: 'NTPC is looking for promising, energetic young engineers for Executive Trainee positions. Training is for 1 year followed by regular placement.',
    qualification: 'Full-time BE / B.Tech',
    minMarks: '65% aggregate (55% for SC/ST/PwBD)',
    selectionProcess: 'GATE score followed by GD and Personal Interview',
    bond: 'Service Agreement Bond of ₹2,50,000',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Out', date: '10 Jun 2026', description: 'Detailed advt released', status: 'COMPLETED' },
      { event: 'Online Registration', date: '18 Jun 2026', description: 'Applications start online', status: 'ACTIVE' },
      { event: 'Last Date of Application', date: '30 Jul 2026', description: 'Last day to apply online', status: 'UPCOMING' },
      { event: 'GD & Interview', date: 'Sep 2026', description: 'Conducted at regional headquarters', status: 'UPCOMING' },
    ],
    importantNotes: [
      'SC/ST/PwBD candidates are exempted from registration fees.',
    ],
  },
  {
    title: "Scientist 'B'",
    organization: 'DRDO',
    organizationFullName: 'Defence R&D Organisation',
    category: 'DEFENCE',
    jobType: 'MIXED',
    eligibleBranches: ['CSE', 'ECE'],
    openToNonEngineering: false,
    numberOfPositions: 496,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: 'Max 28 years (General)',
    eligibility: [
      'First class Bachelor degree in Engineering',
      'Valid GATE score OR IIT/IISc graduates with min 80% aggregate',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://rac.gov.in/',
    deadline: new Date('2026-09-10T23:59:59Z'),
    status: 'OPEN',
    description: 'Recruitment Assessment Centre (RAC) of DRDO invites online applications for direct recruitment of Scientist \'B\' positions. Selection includes written exam and interview for CSE/ECE.',
    qualification: 'BE / B.Tech (ECE / CSE)',
    minMarks: '60% or Equivalent CGPA',
    selectionProcess: 'GATE Score + Descriptive Written Test + Interview',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Notification Published', date: '20 May 2026', description: 'Official notice out', status: 'COMPLETED' },
      { event: 'Online Registration Started', date: '1 Jun 2026', description: 'RAC portal active', status: 'COMPLETED' },
      { event: 'Closing Date', date: '10 Sep 2026', description: 'Submit before 5:00 PM', status: 'ACTIVE' },
      { event: 'Written Descriptive Test', date: 'Oct 2026', description: 'Two descriptive papers of 300 marks', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Descriptive test consists of two papers of 300 marks each.',
    ],
  },
  {
    title: 'Senior Section Engineer (SSE)',
    organization: 'Indian Railways',
    organizationFullName: 'Ministry of Railways (RRB)',
    category: 'RAILWAY',
    jobType: 'NON_GATE',
    eligibleBranches: ['CIVIL', 'ME', 'EE', 'ECE'],
    openToNonEngineering: false,
    numberOfPositions: 3400,
    salary: '₹44,900 - ₹1,42,400/mo',
    ageLimit: '20-34 years',
    eligibility: [
      'Four years Bachelor degree in Engineering (relevant stream)',
      'No GATE score required. Selection based on computer-based exam (CBT).',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://www.rrcb.gov.in/',
    deadline: new Date('2026-08-05T23:59:59Z'),
    status: 'INTERVIEW',
    description: 'Railway Recruitment Boards (RRB) invite online applications for recruitment of SSE posts across various zones. High vacancy recruitment for engineers.',
    qualification: 'BE / B.Tech (Civil/Mech/Elec/ECE)',
    minMarks: 'Pass standard in degree',
    selectionProcess: 'Computer Based Test (CBT 1 & 2) -> Document Verification',
    bond: 'No bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Employment News Notice', date: '15 May 2026', description: 'Preliminary alert published', status: 'COMPLETED' },
      { event: 'Detailed Notification', date: '12 Jun 2026', description: 'RRB websites updated', status: 'COMPLETED' },
      { event: 'Application Last Date', date: '5 Aug 2026', description: 'Submit online before midnight', status: 'ACTIVE' },
      { event: 'CBT Exam Phase 1', date: 'Oct 2026', description: 'Multiple shifts scheduling', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Negative marking of 1/3rd for wrong answers in CBT.',
    ],
  },
  {
    title: 'Executive Trainee',
    organization: 'NPCIL',
    organizationFullName: 'Nuclear Power Corporation of India Ltd',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['ME', 'EE', 'ECE', 'CHEMICAL'],
    openToNonEngineering: false,
    numberOfPositions: 375,
    salary: '₹55,000 - ₹1,60,000/mo',
    ageLimit: 'Max 26 years',
    eligibility: [
      'BE/B.Tech in engineering with minimum 60% marks',
      'Valid GATE 2024, 2025 or 2026 scorecard',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://npcilcareers.co.in/',
    deadline: new Date('2026-06-20T23:59:59Z'),
    status: 'CLOSING_SOON',
    description: 'NPCIL is recruiting Executive Trainees through GATE scorecards. Training for 1 year at DAE units with stipends before absorption.',
    qualification: 'B.Tech / BE (Relevant discipline)',
    minMarks: '60% aggregate',
    selectionProcess: 'GATE Score Shortlisting -> Personal Interview',
    bond: '3 Years Service Bond (₹3,00,000)',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Detailed Advt Out', date: '25 Apr 2026', description: 'Detailed notifications released', status: 'COMPLETED' },
      { event: 'Registration Portal Open', date: '5 May 2026', description: 'Online system active', status: 'COMPLETED' },
      { event: 'Closing of Registrations', date: '20 Jun 2026', description: 'Fees payment closes too', status: 'ACTIVE' },
      { event: 'Interviews at Mumbai', date: 'Jul 2026', description: 'NPCIL headquarters schedules', status: 'UPCOMING' },
    ],
    importantNotes: [
      'GATE score of 2024/2025/2026 is accepted.',
    ],
  },
  {
    title: 'Scientific Officer (OCES/DGFS)',
    organization: 'BARC',
    organizationFullName: 'Bhabha Atomic Research Centre',
    category: 'CENTRAL',
    jobType: 'MIXED',
    eligibleBranches: ['ME', 'CHEMICAL', 'METALLURGY', 'MINING'],
    openToNonEngineering: false,
    numberOfPositions: 220,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: 'Max 26 years',
    eligibility: [
      'BE/B.Tech/B.Sc (Engg) with minimum 60% aggregate',
      'Selection based on Online Exam OR GATE scorecard',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://barconlineexam.com/',
    deadline: new Date('2026-06-12T23:59:59Z'),
    status: 'EXAM_PHASE',
    description: 'BARC Training Schools recruit OCES and DGFS Scientific Officers. Highly competitive program for research-oriented engineers.',
    qualification: 'BE / B.Tech / B.Sc (Engg)',
    minMarks: '60% marks',
    selectionProcess: 'Online Test or GATE Score -> Personal Interview',
    bond: '3 Years Service Bond',
    isNewJob: true,
    showPhases: true,
    timeline: [
      { event: 'Advt Published', date: '10 Feb 2026', description: 'National news notification', status: 'COMPLETED' },
      { event: 'Online Exam Slot Booking', date: 'Apr 2026', description: 'Test booking active', status: 'COMPLETED' },
      { event: 'BARC Online Exam', date: '1-10 Jun 2026', description: 'CBT examination across centres', status: 'COMPLETED' },
      { event: 'Interview Shortlists', date: '15 Jun 2026', description: 'Releasing lists on portal', status: 'ACTIVE' },
      { event: 'Personal Interviews', date: 'Jul-Aug 2026', description: 'At BARC Training School, Mumbai', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Candidates shortlisted through GATE do not need to appear for online test.',
    ],
  },
  {
    title: 'Graduate Engineer Trainee',
    organization: 'HPCL',
    organizationFullName: 'Hindustan Petroleum Corporation Ltd',
    category: 'PSU',
    jobType: 'NON_GATE',
    eligibleBranches: ['ME', 'EE', 'CIVIL', 'CHEMICAL'],
    openToNonEngineering: false,
    numberOfPositions: 290,
    salary: '₹50,000 - ₹1,60,000/mo',
    ageLimit: 'Max 25 years',
    eligibility: [
      'Four-year full time Engineering degree with 60% marks',
      'Selection via computer-based test (CBT) conducted by HPCL',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.hindustanpetroleum.com/',
    deadline: new Date('2026-06-05T23:59:59Z'),
    status: 'CLOSED',
    description: 'HPCL GET recruitment through proprietary examination. High pay package PSU with multiple core discipline posts.',
    qualification: 'Four Year BE / B.Tech',
    minMarks: '60% (50% for SC/ST/PwBD)',
    selectionProcess: 'Computer Based Test -> Group Task -> Personal Interview',
    bond: '4 Years Service Bond (₹1,50,000)',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Advt Out', date: '10 Apr 2026', description: 'Notification detailed copy', status: 'COMPLETED' },
      { event: 'Registration Closes', date: '5 Jun 2026', description: 'Closed on official portal', status: 'COMPLETED' },
      { event: 'CBT Exams', date: 'Jul 2026', description: 'To be held online', status: 'UPCOMING' },
    ],
    importantNotes: [
      'No GATE score required. Proprietary syllabus includes General Aptitude and Technical sections.',
    ],
  },
  {
    title: 'Assistant Engineer (Civil)',
    organization: 'State PWD (UP)',
    organizationFullName: 'Uttar Pradesh Public Works Department',
    category: 'STATE',
    jobType: 'NON_GATE',
    eligibleBranches: ['CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 450,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: '21-40 years',
    eligibility: [
      'Degree in Civil Engineering from recognized university',
      'Recruitment conducted by UPPSC via written exams and interview',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://uppsc.up.nic.in/',
    deadline: new Date('2026-07-22T23:59:59Z'),
    status: 'OPEN',
    description: 'Uttar Pradesh PWD AE recruitment for civil engineers. Permanent state gazetted jobs with standard grade-pay benefits.',
    qualification: 'BE / B.Tech (Civil)',
    minMarks: 'Pass standard in degree',
    selectionProcess: 'State Written Exam -> Interview',
    bond: 'No bond',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Official Advt Released', date: '15 Jun 2026', description: 'UPPSC Advt No A-3/E-1/2026', status: 'COMPLETED' },
      { event: 'Registration Window Open', date: '18 Jun 2026', description: 'Online form link active', status: 'ACTIVE' },
      { event: 'Application Last Date', date: '22 Jul 2026', description: 'Last date to submit forms', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Domicile benefits apply for reserve categories belonging to UP state only.',
    ],
  },
  {
    title: 'Officers/Engineers',
    organization: 'IOCL',
    organizationFullName: 'Indian Oil Corporation Ltd',
    category: 'PSU',
    jobType: 'GATE',
    eligibleBranches: ['CHEMICAL', 'CIVIL', 'EE', 'ME'],
    openToNonEngineering: false,
    numberOfPositions: 600,
    salary: '₹50,000 - ₹1,60,000/mo',
    ageLimit: 'Max 26 years',
    eligibility: [
      'Four year BE/B.Tech or equivalent degree with minimum 65% aggregate',
      'Valid GATE 2026 scorecard in corresponding paper',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://iocl.com/',
    deadline: new Date('2026-07-28T23:59:59Z'),
    status: 'OPEN',
    description: 'Indian Oil recruits Graduate Engineers as Officers through GATE scorecards. Posting across refineries, pipelines, and marketing divisions.',
    qualification: 'B.Tech / BE or equivalent',
    minMarks: '65% aggregate (55% for SC/ST)',
    selectionProcess: 'GATE Score -> Group Discussion -> Personal Interview',
    bond: '3 Years Service Agreement Bond',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Brief Advt Release', date: '10 May 2026', description: 'Preliminary news notification', status: 'COMPLETED' },
      { event: 'Detailed Advt & Apply Link', date: '25 Jun 2026', description: 'IOCL Careers Portal update', status: 'COMPLETED' },
      { event: 'Last Date of Application', date: '28 Jul 2026', description: 'Submit before 11:59 PM', status: 'ACTIVE' },
      { event: 'GD & Interview Calls', date: 'Aug 2026', description: 'Lists published online', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Candidates awaiting final year results are not eligible unless results are declared by last date.',
    ],
  },
  {
    title: 'Research Associate (Aero)',
    organization: 'DRDO - ADE',
    organizationFullName: 'Aeronautical Development Establishment',
    category: 'DEFENCE',
    jobType: 'NON_GATE',
    eligibleBranches: ['ME', 'ECE'],
    openToNonEngineering: false,
    numberOfPositions: 15,
    salary: '₹54,000/mo',
    ageLimit: 'Max 28 years (General)',
    eligibility: [
      'PhD or equivalent degree in Aeronautical/Mechanical/Electronics OR M.Tech with 3 years research experience',
      'No GATE score required. Selection based on interview.',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.drdo.gov.in/',
    deadline: new Date('2026-06-29T23:59:59Z'),
    status: 'OPEN',
    description: 'Aeronautical Development Establishment (ADE) is holding walk-in/scheduled interviews for Research Associates in aerospace development.',
    qualification: 'M.Tech / PhD in engineering',
    minMarks: 'First class in PG',
    selectionProcess: 'Screening -> Interview Board',
    bond: 'No bond',
    isNewJob: true,
    showPhases: false,
    timeline: [
      { event: 'Interview Notification', date: '2 Jun 2026', description: 'ADE advertisement published', status: 'COMPLETED' },
      { event: 'Application Submission Last Date', date: '29 Jun 2026', description: 'Submit via email/post', status: 'ACTIVE' },
      { event: 'Interview Date', date: 'Jul 2026', description: 'Conducted at ADE Bangalore', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Fellowship is initially for a period of two years.',
    ],
  },
  {
    title: 'Deputy Manager (Technical)',
    organization: 'NHAI',
    organizationFullName: 'National Highways Authority of India',
    category: 'CENTRAL',
    jobType: 'GATE',
    eligibleBranches: ['CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 120,
    salary: '₹15,600 - ₹39,100 + GP 5,400/mo',
    ageLimit: 'Max 30 years',
    eligibility: [
      'Degree in Civil Engineering from recognized university',
      'Valid GATE 2026 score in Civil Engineering paper',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://nhai.gov.in/',
    deadline: new Date('2026-06-01T23:59:59Z'),
    status: 'CLOSED',
    description: 'NHAI is recruiting Deputy Managers in Civil engineering through GATE 2026. Permanent jobs under Central Govt.',
    qualification: 'Degree in Civil Engineering',
    minMarks: 'Pass standard in degree',
    selectionProcess: 'GATE Score card selection directly',
    bond: 'Service agreement bond of 2 years',
    isNewJob: false,
    showPhases: false,
    timeline: [
      { event: 'Notification Released', date: '10 Apr 2026', description: 'Detailed notifications on nhai.gov.in', status: 'COMPLETED' },
      { event: 'Application Link Close', date: '1 Jun 2026', description: 'Closed online submissions', status: 'COMPLETED' },
      { event: 'Shortlisted candidates list', date: 'Jul 2026', description: 'Selected list to be published', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Selection is direct based on GATE score; no interviews are scheduled.',
    ],
  },
  {
    title: 'Assistant Manager (Electrical)',
    organization: 'DMRC',
    organizationFullName: 'Delhi Metro Rail Corporation',
    category: 'RAILWAY',
    jobType: 'NON_GATE',
    eligibleBranches: ['EE'],
    openToNonEngineering: false,
    numberOfPositions: 35,
    salary: '₹50,000 - ₹1,60,000/mo',
    ageLimit: '18-30 years',
    eligibility: [
      'BE/B.Tech in Electrical Engineering with minimum 60% marks',
      'Recruitment conducted by DMRC via executive test and screening',
    ],
    eligibilityFinalYear: false,
    applicationUrl: 'https://www.delhimetrorail.com/',
    deadline: new Date('2026-06-15T23:59:59Z'),
    status: 'RESULT',
    description: 'Delhi Metro Rail Corporation AE recruitment for execution and maintenance of electrical assets.',
    qualification: 'BE / B.Tech (Electrical)',
    minMarks: '60% aggregate',
    selectionProcess: 'Computer Based Test -> Medical Examination -> Interview',
    bond: '3 Years Service Bond (₹1,50,000)',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Notification Out', date: '22 Apr 2026', description: 'DMRC Advt AM-01/2026', status: 'COMPLETED' },
      { event: 'Registration Portal Closes', date: '25 May 2026', description: 'Completed', status: 'COMPLETED' },
      { event: 'Admit Card Download', date: '8 Jun 2026', description: 'Active on portal', status: 'COMPLETED' },
      { event: 'CBT Examination', date: '15-18 Jun 2026', description: 'Exams going on', status: 'ACTIVE' },
    ],
    importantNotes: [
      'DMRC tests include a technical domain test and an English proficiency test.',
    ],
  },
  {
    title: 'Assistant Director (Tech)',
    organization: 'BIS',
    organizationFullName: 'Bureau of Indian Standards',
    category: 'CENTRAL',
    jobType: 'MIXED',
    eligibleBranches: ['CSE', 'EE', 'ME', 'CIVIL'],
    openToNonEngineering: false,
    numberOfPositions: 80,
    salary: '₹56,100 - ₹1,77,500/mo',
    ageLimit: 'Max 35 years',
    eligibility: [
      'Bachelor degree in Engineering or equivalent with 60% aggregate',
      'Selection based on online exam and interview. GATE score optional but carries weightage.',
    ],
    eligibilityFinalYear: true,
    applicationUrl: 'https://www.bis.gov.in/',
    deadline: new Date('2026-07-28T23:59:59Z'),
    status: 'OPEN',
    description: 'BIS is hiring Assistant Directors for Technical Administration and Quality Auditing. Executive Group-A central govt positions.',
    qualification: 'Bachelor Degree in Engineering',
    minMarks: '60% aggregate',
    selectionProcess: 'Online Written Test -> Interview',
    bond: 'No bond',
    isNewJob: false,
    showPhases: true,
    timeline: [
      { event: 'Notification Released', date: '10 Jun 2026', description: 'BIS tech-department notice', status: 'COMPLETED' },
      { event: 'Application Form Active', date: '20 Jun 2026', description: 'Registration opens', status: 'ACTIVE' },
      { event: 'Last Date of Application', date: '28 Jul 2026', description: 'Last day to apply online', status: 'UPCOMING' },
    ],
    importantNotes: [
      'Written test pattern consists of general studies, reasoning, English and core engineering fields.',
    ],
  },
];

const sampleNotifications = [
  { text: "BHEL JE Recruitment 2026 – 1200 Posts Open | Apply before 15 Jul" },
  { text: "ISRO Scientist/Engineer SC 2026 – Last Date 30 Jun" },
  { text: "ONGC Graduate Trainee 2026 – Applications Open" },
  { text: "NTPC Engineer Trainee 2026 – 800 Vacancies | GATE Score Required" },
  { text: "DRDO Scientist B 2026 – Written Test on 25 Aug 2026" },
  { text: "BEL Project Engineer 2026 – Apply Before 15 Jul" },
  { text: "HAL Aerospace Engineer 2026 – Written Test Admit Cards Released" }
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing jobs
    await Job.deleteMany({});
    console.log('Cleared existing jobs');

    // Insert sample jobs
    await Job.insertMany(sampleJobs);
    console.log(`✅ Successfully seeded ${sampleJobs.length} job postings!`);

    // Clear existing notifications
    await Notification.deleteMany({});
    console.log('Cleared existing notifications');

    // Insert sample notifications
    await Notification.insertMany(sampleNotifications);
    console.log(`✅ Successfully seeded ${sampleNotifications.length} notifications!`);

    await mongoose.connection.close();
    console.log('Disconnected from MongoDB');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();
